name: XCS330_CUDA
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - cloudpickle=2.2.1
  - cycler=0.11.0
  - h5py=3.9.0
  - lockfile=0.12.2
  - opt-einsum=3.3.0
  - packaging=23.1
  - pandas=2.1.4
  - pickleshare=0.7.5
  - python-dateutil=2.8.2
  - requests=2.31.0
  - scipy=1.11.4
  - six=1.16.0
  - scikit-learn=1.3.0
  - tensorboard=2.12.1
  - pytest=7.4.0
  - imageio=2.31.4
  - svglib=1.5.1
  - googledrivedownloader=0.4
  - matplotlib=3.8.0
  - pip=23.3.1
  - pip:
    - timeout_decorator==0.5.0
    - "--find-links https://download.pytorch.org/whl/torch_stable.html"
    - torch==2.1.2+cu118
    - rouge-score==0.1.2
    # Manage the below packages over pip to avoid segmentation fault in transformers on Mac
    - huggingface-hub==0.20.1
    - transformers==4.36.2
    - datasets==2.16.1
    - numpy==1.26.2
